/**
 * generated by Xtext 2.19.0
 */
package requirements.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import requirements.dsl.RDSLRuntimeModule;
import requirements.dsl.RDSLStandaloneSetup;
import requirements.dsl.ide.RDSLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RDSLIdeSetup extends RDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    RDSLRuntimeModule _rDSLRuntimeModule = new RDSLRuntimeModule();
    RDSLIdeModule _rDSLIdeModule = new RDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_rDSLRuntimeModule, _rDSLIdeModule));
  }
}
