/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.usecases.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UseCasesDslRuntimeModule extends AbstractUseCasesDslRuntimeModule {
}
