@startuml
digraph mindmap {
"Gorgeous Food Application"
"Gorgeous Food Application" -> "Unserved Meal"
"Unserved Meal"
"Unexpensive"
"Balanced"
"Frozen"
"Elegant"
"Packaged"
"Labeled"
"Expiration Date"
"Production Date"
"ID"
"Designation"
"Inventory Managed By Software"
"Meal in Inventory"
"Time"
"Location"
"Allergens"
"Ingredients"
"Nutritional Data"
"Type"
"Designation"
"Type Of User Who Purchased"
"Unserved Meal" -> "Balanced"
"Unserved Meal" -> "Unexpensive"
"Unserved Meal" -> "Frozen"
"Unserved Meal" -> "Elegant"
"Unserved Meal" -> "Packaged"
"Packaged" -> "Labeled"
"Labeled" -> "Designation"
"Labeled" -> "ID"
"Labeled" -> "Production Date"
"Labeled" -> "Expiration Date"
"Inventory Managed By Software" -> "Meal in Inventory"
"Meal in Inventory" -> "Time"
"Meal in Inventory" -> "Location"
"Meal in Inventory" -> "Allergens"
"Meal in Inventory" -> "Ingredients"
"Meal in Inventory" -> "Nutritional Data"
"Meal in Inventory" -> "Type"
"Meal in Inventory" -> "Designation"
"Meal in Inventory" -> "Type Of User Who Purchased"
}
@enduml
