/**
 * generated by Xtext 2.19.0
 */
package requirements.dsl.validation;

import requirements.dsl.validation.AbstractRDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RDSLValidator extends AbstractRDSLValidator {
}
