/**
 * generated by Xtext 2.19.0
 */
package requirements.dsl.ide;

import requirements.dsl.ide.AbstractRDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RDSLIdeModule extends AbstractRDSLIdeModule {
}
