/**
 * generated by Xtext 2.19.0
 */
package requirements.dsl.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;
import requirements.dsl.tests.RDSLInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(RDSLInjectorProvider.class)
@SuppressWarnings("all")
public class RDSLParsingTest {
}
