/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NavStandaloneSetup extends NavStandaloneSetupGenerated {

	def static void doSetup() {
		new NavStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
