/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class NavUiModule extends AbstractNavUiModule {
}
