/*
 * generated by Xtext 2.12.0
 */
grammar InternalUseCase;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package pt.isep.edom.project.c0.dsl.usecase.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package pt.isep.edom.project.c0.dsl.usecase.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import pt.isep.edom.project.c0.dsl.usecase.services.UseCaseGrammarAccess;

}

@parser::members {

 	private UseCaseGrammarAccess grammarAccess;

    public InternalUseCaseParser(TokenStream input, UseCaseGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "UseCaseModel";
   	}

   	@Override
   	protected UseCaseGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleUseCaseModel
entryRuleUseCaseModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getUseCaseModelRule()); }
	iv_ruleUseCaseModel=ruleUseCaseModel
	{ $current=$iv_ruleUseCaseModel.current; }
	EOF;

// Rule UseCaseModel
ruleUseCaseModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getUseCaseModelAccess().getUseCaseModelAction_0(),
					$current);
			}
		)
		otherlv_1='UseCaseModel'
		{
			newLeafNode(otherlv_1, grammarAccess.getUseCaseModelAccess().getUseCaseModelKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getUseCaseModelAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getUseCaseModelRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"pt.isep.edom.project.c0.dsl.usecase.UseCase.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getUseCaseModelAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_4='actor'
			{
				newLeafNode(otherlv_4, grammarAccess.getUseCaseModelAccess().getActorKeyword_4_0());
			}
			otherlv_5='{'
			{
				newLeafNode(otherlv_5, grammarAccess.getUseCaseModelAccess().getLeftCurlyBracketKeyword_4_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getUseCaseModelAccess().getActorActorParserRuleCall_4_2_0());
					}
					lv_actor_6_0=ruleActor
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getUseCaseModelRule());
						}
						add(
							$current,
							"actor",
							lv_actor_6_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.Actor");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_7=','
				{
					newLeafNode(otherlv_7, grammarAccess.getUseCaseModelAccess().getCommaKeyword_4_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getUseCaseModelAccess().getActorActorParserRuleCall_4_3_1_0());
						}
						lv_actor_8_0=ruleActor
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getUseCaseModelRule());
							}
							add(
								$current,
								"actor",
								lv_actor_8_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.Actor");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_9='}'
			{
				newLeafNode(otherlv_9, grammarAccess.getUseCaseModelAccess().getRightCurlyBracketKeyword_4_4());
			}
		)?
		(
			otherlv_10='association'
			{
				newLeafNode(otherlv_10, grammarAccess.getUseCaseModelAccess().getAssociationKeyword_5_0());
			}
			otherlv_11='{'
			{
				newLeafNode(otherlv_11, grammarAccess.getUseCaseModelAccess().getLeftCurlyBracketKeyword_5_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getUseCaseModelAccess().getAssociationAssociationParserRuleCall_5_2_0());
					}
					lv_association_12_0=ruleAssociation
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getUseCaseModelRule());
						}
						add(
							$current,
							"association",
							lv_association_12_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.Association");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_13=','
				{
					newLeafNode(otherlv_13, grammarAccess.getUseCaseModelAccess().getCommaKeyword_5_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getUseCaseModelAccess().getAssociationAssociationParserRuleCall_5_3_1_0());
						}
						lv_association_14_0=ruleAssociation
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getUseCaseModelRule());
							}
							add(
								$current,
								"association",
								lv_association_14_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.Association");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_15='}'
			{
				newLeafNode(otherlv_15, grammarAccess.getUseCaseModelAccess().getRightCurlyBracketKeyword_5_4());
			}
		)?
		(
			otherlv_16='usecase'
			{
				newLeafNode(otherlv_16, grammarAccess.getUseCaseModelAccess().getUsecaseKeyword_6_0());
			}
			otherlv_17='{'
			{
				newLeafNode(otherlv_17, grammarAccess.getUseCaseModelAccess().getLeftCurlyBracketKeyword_6_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getUseCaseModelAccess().getUsecaseUseCaseParserRuleCall_6_2_0());
					}
					lv_usecase_18_0=ruleUseCase
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getUseCaseModelRule());
						}
						add(
							$current,
							"usecase",
							lv_usecase_18_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.UseCase");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_19=','
				{
					newLeafNode(otherlv_19, grammarAccess.getUseCaseModelAccess().getCommaKeyword_6_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getUseCaseModelAccess().getUsecaseUseCaseParserRuleCall_6_3_1_0());
						}
						lv_usecase_20_0=ruleUseCase
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getUseCaseModelRule());
							}
							add(
								$current,
								"usecase",
								lv_usecase_20_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.UseCase");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_21='}'
			{
				newLeafNode(otherlv_21, grammarAccess.getUseCaseModelAccess().getRightCurlyBracketKeyword_6_4());
			}
		)?
		otherlv_22='}'
		{
			newLeafNode(otherlv_22, grammarAccess.getUseCaseModelAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleActor
entryRuleActor returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getActorRule()); }
	iv_ruleActor=ruleActor
	{ $current=$iv_ruleActor.current; }
	EOF;

// Rule Actor
ruleActor returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getActorAccess().getActorAction_0(),
					$current);
			}
		)
		otherlv_1='Actor'
		{
			newLeafNode(otherlv_1, grammarAccess.getActorAccess().getActorKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getActorAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getActorRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"pt.isep.edom.project.c0.dsl.usecase.UseCase.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleAssociation
entryRuleAssociation returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAssociationRule()); }
	iv_ruleAssociation=ruleAssociation
	{ $current=$iv_ruleAssociation.current; }
	EOF;

// Rule Association
ruleAssociation returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Association'
		{
			newLeafNode(otherlv_0, grammarAccess.getAssociationAccess().getAssociationKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAssociationAccess().getNameEStringParserRuleCall_1_0());
				}
				lv_name_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAssociationRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"pt.isep.edom.project.c0.dsl.usecase.UseCase.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getAssociationAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='actor'
		{
			newLeafNode(otherlv_3, grammarAccess.getAssociationAccess().getActorKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAssociationRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getAssociationAccess().getActorActorCrossReference_4_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='usecase'
		{
			newLeafNode(otherlv_5, grammarAccess.getAssociationAccess().getUsecaseKeyword_5());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAssociationRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getAssociationAccess().getUsecaseUseCaseCrossReference_6_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getAssociationAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleUseCase
entryRuleUseCase returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getUseCaseRule()); }
	iv_ruleUseCase=ruleUseCase
	{ $current=$iv_ruleUseCase.current; }
	EOF;

// Rule UseCase
ruleUseCase returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getUseCaseAccess().getUseCaseAction_0(),
					$current);
			}
		)
		otherlv_1='UseCase'
		{
			newLeafNode(otherlv_1, grammarAccess.getUseCaseAccess().getUseCaseKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getUseCaseAccess().getNameEStringParserRuleCall_2_0());
				}
				lv_name_2_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getUseCaseRule());
					}
					set(
						$current,
						"name",
						lv_name_2_0,
						"pt.isep.edom.project.c0.dsl.usecase.UseCase.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getUseCaseAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			otherlv_4='extend'
			{
				newLeafNode(otherlv_4, grammarAccess.getUseCaseAccess().getExtendKeyword_4_0());
			}
			otherlv_5='{'
			{
				newLeafNode(otherlv_5, grammarAccess.getUseCaseAccess().getLeftCurlyBracketKeyword_4_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getUseCaseAccess().getExtendExtendParserRuleCall_4_2_0());
					}
					lv_extend_6_0=ruleExtend
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getUseCaseRule());
						}
						add(
							$current,
							"extend",
							lv_extend_6_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.Extend");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_7=','
				{
					newLeafNode(otherlv_7, grammarAccess.getUseCaseAccess().getCommaKeyword_4_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getUseCaseAccess().getExtendExtendParserRuleCall_4_3_1_0());
						}
						lv_extend_8_0=ruleExtend
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getUseCaseRule());
							}
							add(
								$current,
								"extend",
								lv_extend_8_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.Extend");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_9='}'
			{
				newLeafNode(otherlv_9, grammarAccess.getUseCaseAccess().getRightCurlyBracketKeyword_4_4());
			}
		)?
		(
			otherlv_10='include'
			{
				newLeafNode(otherlv_10, grammarAccess.getUseCaseAccess().getIncludeKeyword_5_0());
			}
			otherlv_11='{'
			{
				newLeafNode(otherlv_11, grammarAccess.getUseCaseAccess().getLeftCurlyBracketKeyword_5_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getUseCaseAccess().getIncludeIncludeParserRuleCall_5_2_0());
					}
					lv_include_12_0=ruleInclude
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getUseCaseRule());
						}
						add(
							$current,
							"include",
							lv_include_12_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.Include");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_13=','
				{
					newLeafNode(otherlv_13, grammarAccess.getUseCaseAccess().getCommaKeyword_5_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getUseCaseAccess().getIncludeIncludeParserRuleCall_5_3_1_0());
						}
						lv_include_14_0=ruleInclude
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getUseCaseRule());
							}
							add(
								$current,
								"include",
								lv_include_14_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.Include");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_15='}'
			{
				newLeafNode(otherlv_15, grammarAccess.getUseCaseAccess().getRightCurlyBracketKeyword_5_4());
			}
		)?
		(
			otherlv_16='comment'
			{
				newLeafNode(otherlv_16, grammarAccess.getUseCaseAccess().getCommentKeyword_6_0());
			}
			otherlv_17='{'
			{
				newLeafNode(otherlv_17, grammarAccess.getUseCaseAccess().getLeftCurlyBracketKeyword_6_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getUseCaseAccess().getCommentCommentParserRuleCall_6_2_0());
					}
					lv_comment_18_0=ruleComment
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getUseCaseRule());
						}
						add(
							$current,
							"comment",
							lv_comment_18_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.Comment");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_19=','
				{
					newLeafNode(otherlv_19, grammarAccess.getUseCaseAccess().getCommaKeyword_6_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getUseCaseAccess().getCommentCommentParserRuleCall_6_3_1_0());
						}
						lv_comment_20_0=ruleComment
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getUseCaseRule());
							}
							add(
								$current,
								"comment",
								lv_comment_20_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.Comment");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_21='}'
			{
				newLeafNode(otherlv_21, grammarAccess.getUseCaseAccess().getRightCurlyBracketKeyword_6_4());
			}
		)?
		otherlv_22='}'
		{
			newLeafNode(otherlv_22, grammarAccess.getUseCaseAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRuleExtend
entryRuleExtend returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getExtendRule()); }
	iv_ruleExtend=ruleExtend
	{ $current=$iv_ruleExtend.current; }
	EOF;

// Rule Extend
ruleExtend returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Extend'
		{
			newLeafNode(otherlv_0, grammarAccess.getExtendAccess().getExtendKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getExtendAccess().getNameEStringParserRuleCall_1_0());
				}
				lv_name_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getExtendRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"pt.isep.edom.project.c0.dsl.usecase.UseCase.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getExtendAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='usecase'
		{
			newLeafNode(otherlv_3, grammarAccess.getExtendAccess().getUsecaseKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getExtendRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getExtendAccess().getUsecaseUseCaseCrossReference_4_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
<<<<<<< HEAD
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getExtendAccess().getRightCurlyBracketKeyword_5());
=======
		(
			otherlv_5='comment'
			{
				newLeafNode(otherlv_5, grammarAccess.getExtendAccess().getCommentKeyword_5_0());
			}
			otherlv_6='{'
			{
				newLeafNode(otherlv_6, grammarAccess.getExtendAccess().getLeftCurlyBracketKeyword_5_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getExtendAccess().getCommentCommentParserRuleCall_5_2_0());
					}
					lv_comment_7_0=ruleComment
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getExtendRule());
						}
						add(
							$current,
							"comment",
							lv_comment_7_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.Comment");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_8=','
				{
					newLeafNode(otherlv_8, grammarAccess.getExtendAccess().getCommaKeyword_5_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getExtendAccess().getCommentCommentParserRuleCall_5_3_1_0());
						}
						lv_comment_9_0=ruleComment
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getExtendRule());
							}
							add(
								$current,
								"comment",
								lv_comment_9_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.Comment");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_10='}'
			{
				newLeafNode(otherlv_10, grammarAccess.getExtendAccess().getRightCurlyBracketKeyword_5_4());
			}
		)?
		otherlv_11='}'
		{
			newLeafNode(otherlv_11, grammarAccess.getExtendAccess().getRightCurlyBracketKeyword_6());
>>>>>>> 6ba51290ef074f452a9501b6e0535b5b1dd23617
		}
	)
;

// Entry rule entryRuleInclude
entryRuleInclude returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getIncludeRule()); }
	iv_ruleInclude=ruleInclude
	{ $current=$iv_ruleInclude.current; }
	EOF;

// Rule Include
ruleInclude returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Include'
		{
			newLeafNode(otherlv_0, grammarAccess.getIncludeAccess().getIncludeKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getIncludeAccess().getNameEStringParserRuleCall_1_0());
				}
				lv_name_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getIncludeRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"pt.isep.edom.project.c0.dsl.usecase.UseCase.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getIncludeAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='usecase'
		{
			newLeafNode(otherlv_3, grammarAccess.getIncludeAccess().getUsecaseKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getIncludeRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getIncludeAccess().getUsecaseUseCaseCrossReference_4_0());
				}
				ruleEString
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
<<<<<<< HEAD
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getIncludeAccess().getRightCurlyBracketKeyword_5());
=======
		(
			otherlv_5='comment'
			{
				newLeafNode(otherlv_5, grammarAccess.getIncludeAccess().getCommentKeyword_5_0());
			}
			otherlv_6='{'
			{
				newLeafNode(otherlv_6, grammarAccess.getIncludeAccess().getLeftCurlyBracketKeyword_5_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getIncludeAccess().getCommentCommentParserRuleCall_5_2_0());
					}
					lv_comment_7_0=ruleComment
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getIncludeRule());
						}
						add(
							$current,
							"comment",
							lv_comment_7_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.Comment");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_8=','
				{
					newLeafNode(otherlv_8, grammarAccess.getIncludeAccess().getCommaKeyword_5_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getIncludeAccess().getCommentCommentParserRuleCall_5_3_1_0());
						}
						lv_comment_9_0=ruleComment
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getIncludeRule());
							}
							add(
								$current,
								"comment",
								lv_comment_9_0,
								"pt.isep.edom.project.c0.dsl.usecase.UseCase.Comment");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_10='}'
			{
				newLeafNode(otherlv_10, grammarAccess.getIncludeAccess().getRightCurlyBracketKeyword_5_4());
			}
		)?
		otherlv_11='}'
		{
			newLeafNode(otherlv_11, grammarAccess.getIncludeAccess().getRightCurlyBracketKeyword_6());
>>>>>>> 6ba51290ef074f452a9501b6e0535b5b1dd23617
		}
	)
;

// Entry rule entryRuleComment
entryRuleComment returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCommentRule()); }
	iv_ruleComment=ruleComment
	{ $current=$iv_ruleComment.current; }
	EOF;

// Rule Comment
ruleComment returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				$current = forceCreateModelElement(
					grammarAccess.getCommentAccess().getCommentAction_0(),
					$current);
			}
		)
		otherlv_1='Comment'
		{
			newLeafNode(otherlv_1, grammarAccess.getCommentAccess().getCommentKeyword_1());
		}
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getCommentAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			otherlv_3='description'
			{
				newLeafNode(otherlv_3, grammarAccess.getCommentAccess().getDescriptionKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getCommentAccess().getDescriptionEStringParserRuleCall_3_1_0());
					}
					lv_description_4_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getCommentRule());
						}
						set(
							$current,
							"description",
							lv_description_4_0,
							"pt.isep.edom.project.c0.dsl.usecase.UseCase.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_5='}'
		{
			newLeafNode(otherlv_5, grammarAccess.getCommentAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
