/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c1.dsl.nav.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.edom.project.c1.dsl.nav.ide.contentassist.antlr.internal.InternalNavParser;
import pt.isep.edom.project.c1.dsl.nav.services.NavGrammarAccess;

public class NavParser extends AbstractContentAssistParser {

	@Inject
	private NavGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalNavParser createParser() {
		InternalNavParser result = new InternalNavParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getNavModelAccess().getGroup(), "rule__NavModel__Group__0");
					put(grammarAccess.getNavModelAccess().getGroup_4(), "rule__NavModel__Group_4__0");
					put(grammarAccess.getMenuAccess().getGroup(), "rule__Menu__Group__0");
					put(grammarAccess.getMenuAccess().getGroup_4(), "rule__Menu__Group_4__0");
					put(grammarAccess.getMenuAccess().getGroup_4_3(), "rule__Menu__Group_4_3__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getNavModelAccess().getNameAssignment_2(), "rule__NavModel__NameAssignment_2");
					put(grammarAccess.getNavModelAccess().getMenuAssignment_4_1(), "rule__NavModel__MenuAssignment_4_1");
					put(grammarAccess.getMenuAccess().getNameAssignment_2(), "rule__Menu__NameAssignment_2");
					put(grammarAccess.getMenuAccess().getPagesAssignment_4_2(), "rule__Menu__PagesAssignment_4_2");
					put(grammarAccess.getMenuAccess().getPagesAssignment_4_3_1(), "rule__Menu__PagesAssignment_4_3_1");
					put(grammarAccess.getPageAccess().getNameAssignment_2(), "rule__Page__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public NavGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NavGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
