@startuml
digraph GFA {
"Gorgeous Food Application"
"Functional Requirements"
"Manage Meals"
"Save Meal"
"Version 0.0.1"
"Save Meal" -> "Version 0.0.1"
"Show Meal Designation"
"Version 0.0.1"
"Show Meal Designation" -> "Version 0.0.1"
"Show Meal Nutritional Data"
"Version 0.0.1"
"Show Meal Nutritional Data" -> "Version 0.0.1"
"Show Meal Type"
"Version 0.0.1"
"Show Meal Type" -> "Version 0.0.1"
"Show Meal Location"
"Version 0.0.1"
"Show Meal Location" -> "Version 0.0.1"
"Show Meal Price"
"Version 0.0.1"
"Show Meal Price" -> "Version 0.0.1"
"List Meal Ingreditens"
"Version 0.0.1"
"List Meal Ingreditens" -> "Version 0.0.1"
"List Meal Allergens"
"Version 0.0.1"
"List Meal Allergens" -> "Version 0.0.1"
"Check Meal Availability"
"Version 0.0.1"
"Check Meal Availability" -> "Version 0.0.1"
"Pay Meal"
"Version 0.0.1"
"Pay Meal" -> "Version 0.0.1"
"Manage Meals" -> "Save Meal"
"Manage Meals" -> "Show Meal Designation"
"Manage Meals" -> "Show Meal Nutritional Data"
"Manage Meals" -> "Show Meal Type"
"Manage Meals" -> "Show Meal Location"
"Manage Meals" -> "Show Meal Price"
"Manage Meals" -> "List Meal Ingreditens"
"Manage Meals" -> "List Meal Allergens"
"Manage Meals" -> "Check Meal Availability"
"Manage Meals" -> "Pay Meal"
"Manage Unserved Meals"
"Save Unserved Meal"
"Version 0.0.1"
"Save Unserved Meal" -> "Version 0.0.1"
"Show Unserved Meal Identification Number"
"Version 0.0.1"
"Show Unserved Meal Identification Number" -> "Version 0.0.1"
"Show Unserved Meal Designation"
"Version 0.0.1"
"Show Unserved Meal Designation" -> "Version 0.0.1"
"Show Unserved Meal Production Date"
"Version 0.0.1"
"Show Unserved Meal Production Date" -> "Version 0.0.1"
"Show Unserved Meal Expiration Date"
"Version 0.0.1"
"Show Unserved Meal Expiration Date" -> "Version 0.0.1"
"Show Unserved Meal State"
"Version 0.0.1"
"Show Unserved Meal State" -> "Version 0.0.1"
"Manage Unserved Meals" -> "Save Unserved Meal"
"Manage Unserved Meals" -> "Show Unserved Meal Identification Number"
"Manage Unserved Meals" -> "Show Unserved Meal Designation"
"Manage Unserved Meals" -> "Show Unserved Meal Production Date"
"Manage Unserved Meals" -> "Show Unserved Meal Expiration Date"
"Manage Unserved Meals" -> "Show Unserved Meal State"
"Functional Requirements" -> "Manage Meals"
"Functional Requirements" -> "Manage Unserved Meals"
"Quality Attributes"
"Gorgeous Food Application" -> "Functional Requirements"
"Gorgeous Food Application" -> "Quality Attributes"

}
@enduml
