/*
 * generated by Xtext 2.19.0
 */
package requirements.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import requirements.dsl.parser.antlr.internal.InternalRDSLParser;
import requirements.dsl.services.RDSLGrammarAccess;

public class RDSLParser extends AbstractAntlrParser {

	@Inject
	private RDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRDSLParser createParser(XtextTokenStream stream) {
		return new InternalRDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
