/*
 * generated by Xtext 2.19.0
 */
package requirements.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import requirements.dsl.ui.internal.DslActivator;

public class RDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("requirements.dsl.RDSL");
	}

}
