/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c4.dsl.dbase.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.edom.project.c4.dsl.dbase.ide.contentassist.antlr.internal.InternalDbaseParser;
import pt.isep.edom.project.c4.dsl.dbase.services.DbaseGrammarAccess;

public class DbaseParser extends AbstractContentAssistParser {

	@Inject
	private DbaseGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDbaseParser createParser() {
		InternalDbaseParser result = new InternalDbaseParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getColumnTypeAccess().getAlternatives(), "rule__ColumnType__Alternatives");
					put(grammarAccess.getDbaseModelAccess().getGroup(), "rule__DbaseModel__Group__0");
					put(grammarAccess.getDbaseModelAccess().getGroup_4(), "rule__DbaseModel__Group_4__0");
					put(grammarAccess.getDbaseModelAccess().getGroup_4_3(), "rule__DbaseModel__Group_4_3__0");
					put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
					put(grammarAccess.getTableAccess().getGroup_4(), "rule__Table__Group_4__0");
					put(grammarAccess.getTableAccess().getGroup_5(), "rule__Table__Group_5__0");
					put(grammarAccess.getTableAccess().getGroup_5_3(), "rule__Table__Group_5_3__0");
					put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
					put(grammarAccess.getColumnAccess().getGroup_5(), "rule__Column__Group_5__0");
					put(grammarAccess.getColumnAccess().getGroup_6(), "rule__Column__Group_6__0");
					put(grammarAccess.getColumnAccess().getGroup_6_3(), "rule__Column__Group_6_3__0");
					put(grammarAccess.getDbaseModelAccess().getNameAssignment_2(), "rule__DbaseModel__NameAssignment_2");
					put(grammarAccess.getDbaseModelAccess().getTablesAssignment_4_2(), "rule__DbaseModel__TablesAssignment_4_2");
					put(grammarAccess.getDbaseModelAccess().getTablesAssignment_4_3_1(), "rule__DbaseModel__TablesAssignment_4_3_1");
					put(grammarAccess.getTableAccess().getNameAssignment_2(), "rule__Table__NameAssignment_2");
					put(grammarAccess.getTableAccess().getEntityAssignment_4_1(), "rule__Table__EntityAssignment_4_1");
					put(grammarAccess.getTableAccess().getColumnsAssignment_5_2(), "rule__Table__ColumnsAssignment_5_2");
					put(grammarAccess.getTableAccess().getColumnsAssignment_5_3_1(), "rule__Table__ColumnsAssignment_5_3_1");
					put(grammarAccess.getColumnAccess().getKeyAssignment_1(), "rule__Column__KeyAssignment_1");
					put(grammarAccess.getColumnAccess().getNameAssignment_3(), "rule__Column__NameAssignment_3");
					put(grammarAccess.getColumnAccess().getTypeAssignment_5_1(), "rule__Column__TypeAssignment_5_1");
					put(grammarAccess.getColumnAccess().getForeignKeyAssignment_6_2(), "rule__Column__ForeignKeyAssignment_6_2");
					put(grammarAccess.getColumnAccess().getForeignKeyAssignment_6_3_1(), "rule__Column__ForeignKeyAssignment_6_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DbaseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DbaseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
