/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c2.dsl.rest.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RestGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RestModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c2.dsl.rest.Rest.RestModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRestModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRestModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUrlKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUrlAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUrlEStringParserRuleCall_4_1_0 = (RuleCall)cUrlAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResourcesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cResourcesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cResourcesResourceParserRuleCall_5_2_0 = (RuleCall)cResourcesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cResourcesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cResourcesResourceParserRuleCall_5_3_1_0 = (RuleCall)cResourcesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//RestModel:
		//	{RestModel}
		//	'RestModel'
		//	name=EString
		//	'{' ('url' url=EString)? ('resources' '{' resources+=Resource ("," resources+=Resource)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RestModel} 'RestModel' name=EString '{' ('url' url=EString)? ('resources' '{' resources+=Resource (","
		//resources+=Resource)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{RestModel}
		public Action getRestModelAction_0() { return cRestModelAction_0; }
		
		//'RestModel'
		public Keyword getRestModelKeyword_1() { return cRestModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('url' url=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'url'
		public Keyword getUrlKeyword_4_0() { return cUrlKeyword_4_0; }
		
		//url=EString
		public Assignment getUrlAssignment_4_1() { return cUrlAssignment_4_1; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_4_1_0() { return cUrlEStringParserRuleCall_4_1_0; }
		
		//('resources' '{' resources+=Resource ("," resources+=Resource)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'resources'
		public Keyword getResourcesKeyword_5_0() { return cResourcesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//resources+=Resource
		public Assignment getResourcesAssignment_5_2() { return cResourcesAssignment_5_2; }
		
		//Resource
		public RuleCall getResourcesResourceParserRuleCall_5_2_0() { return cResourcesResourceParserRuleCall_5_2_0; }
		
		//("," resources+=Resource)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//resources+=Resource
		public Assignment getResourcesAssignment_5_3_1() { return cResourcesAssignment_5_3_1; }
		
		//Resource
		public RuleCall getResourcesResourceParserRuleCall_5_3_1_0() { return cResourcesResourceParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c2.dsl.rest.Rest.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c2.dsl.rest.Rest.Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cResourceAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cPutAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cPutPutKeyword_1_0 = (Keyword)cPutAssignment_1.eContents().get(0);
		private final Assignment cPostAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cPostPostKeyword_2_0 = (Keyword)cPostAssignment_2.eContents().get(0);
		private final Assignment cDeleteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cDeleteDeleteKeyword_3_0 = (Keyword)cDeleteAssignment_3.eContents().get(0);
		private final Assignment cGetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cGetGetKeyword_4_0 = (Keyword)cGetAssignment_4.eContents().get(0);
		private final Keyword cResourceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameEStringParserRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cEntityKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cEntityAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cEntityEStringParserRuleCall_8_1_0 = (RuleCall)cEntityAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cReferenceKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cReferenceAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final CrossReference cReferenceResourceCrossReference_9_2_0 = (CrossReference)cReferenceAssignment_9_2.eContents().get(0);
		private final RuleCall cReferenceResourceEStringParserRuleCall_9_2_0_1 = (RuleCall)cReferenceResourceCrossReference_9_2_0.eContents().get(1);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cReferenceAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final CrossReference cReferenceResourceCrossReference_9_3_1_0 = (CrossReference)cReferenceAssignment_9_3_1.eContents().get(0);
		private final RuleCall cReferenceResourceEStringParserRuleCall_9_3_1_0_1 = (RuleCall)cReferenceResourceCrossReference_9_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cSubresourceKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cSubresourceAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cSubresourceResourceParserRuleCall_10_2_0 = (RuleCall)cSubresourceAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cSubresourceAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cSubresourceResourceParserRuleCall_10_3_1_0 = (RuleCall)cSubresourceAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Resource:
		//	{Resource} put?='put'?
		//	post?='post'?
		//	delete?='delete'?
		//	get?='get'?
		//	'Resource'
		//	name=EString
		//	'{' ('entity' entity=EString)? ('reference' '(' reference+=[Resource|EString] ("," reference+=[Resource|EString])*
		//	')')? ('subresource' '{' subresource+=Resource ("," subresource+=Resource)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Resource} put?='put'? post?='post'? delete?='delete'? get?='get'? 'Resource' name=EString '{' ('entity'
		//entity=EString)? ('reference' '(' reference+=[Resource|EString] ("," reference+=[Resource|EString])* ')')?
		//('subresource' '{' subresource+=Resource ("," subresource+=Resource)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Resource}
		public Action getResourceAction_0() { return cResourceAction_0; }
		
		//put?='put'?
		public Assignment getPutAssignment_1() { return cPutAssignment_1; }
		
		//'put'
		public Keyword getPutPutKeyword_1_0() { return cPutPutKeyword_1_0; }
		
		//post?='post'?
		public Assignment getPostAssignment_2() { return cPostAssignment_2; }
		
		//'post'
		public Keyword getPostPostKeyword_2_0() { return cPostPostKeyword_2_0; }
		
		//delete?='delete'?
		public Assignment getDeleteAssignment_3() { return cDeleteAssignment_3; }
		
		//'delete'
		public Keyword getDeleteDeleteKeyword_3_0() { return cDeleteDeleteKeyword_3_0; }
		
		//get?='get'?
		public Assignment getGetAssignment_4() { return cGetAssignment_4; }
		
		//'get'
		public Keyword getGetGetKeyword_4_0() { return cGetGetKeyword_4_0; }
		
		//'Resource'
		public Keyword getResourceKeyword_5() { return cResourceKeyword_5; }
		
		//name=EString
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_6_0() { return cNameEStringParserRuleCall_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//('entity' entity=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'entity'
		public Keyword getEntityKeyword_8_0() { return cEntityKeyword_8_0; }
		
		//entity=EString
		public Assignment getEntityAssignment_8_1() { return cEntityAssignment_8_1; }
		
		//EString
		public RuleCall getEntityEStringParserRuleCall_8_1_0() { return cEntityEStringParserRuleCall_8_1_0; }
		
		//('reference' '(' reference+=[Resource|EString] ("," reference+=[Resource|EString])* ')')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'reference'
		public Keyword getReferenceKeyword_9_0() { return cReferenceKeyword_9_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_9_1() { return cLeftParenthesisKeyword_9_1; }
		
		//reference+=[Resource|EString]
		public Assignment getReferenceAssignment_9_2() { return cReferenceAssignment_9_2; }
		
		//[Resource|EString]
		public CrossReference getReferenceResourceCrossReference_9_2_0() { return cReferenceResourceCrossReference_9_2_0; }
		
		//EString
		public RuleCall getReferenceResourceEStringParserRuleCall_9_2_0_1() { return cReferenceResourceEStringParserRuleCall_9_2_0_1; }
		
		//("," reference+=[Resource|EString])*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//reference+=[Resource|EString]
		public Assignment getReferenceAssignment_9_3_1() { return cReferenceAssignment_9_3_1; }
		
		//[Resource|EString]
		public CrossReference getReferenceResourceCrossReference_9_3_1_0() { return cReferenceResourceCrossReference_9_3_1_0; }
		
		//EString
		public RuleCall getReferenceResourceEStringParserRuleCall_9_3_1_0_1() { return cReferenceResourceEStringParserRuleCall_9_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9_4() { return cRightParenthesisKeyword_9_4; }
		
		//('subresource' '{' subresource+=Resource ("," subresource+=Resource)* '}')?
		public Group getGroup_10() { return cGroup_10; }
		
		//'subresource'
		public Keyword getSubresourceKeyword_10_0() { return cSubresourceKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//subresource+=Resource
		public Assignment getSubresourceAssignment_10_2() { return cSubresourceAssignment_10_2; }
		
		//Resource
		public RuleCall getSubresourceResourceParserRuleCall_10_2_0() { return cSubresourceResourceParserRuleCall_10_2_0; }
		
		//("," subresource+=Resource)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//subresource+=Resource
		public Assignment getSubresourceAssignment_10_3_1() { return cSubresourceAssignment_10_3_1; }
		
		//Resource
		public RuleCall getSubresourceResourceParserRuleCall_10_3_1_0() { return cSubresourceResourceParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pt.isep.edom.project.c2.dsl.rest.Rest.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	private final RestModelElements pRestModel;
	private final EStringElements pEString;
	private final ResourceElements pResource;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RestGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRestModel = new RestModelElements();
		this.pEString = new EStringElements();
		this.pResource = new ResourceElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("pt.isep.edom.project.c2.dsl.rest.Rest".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RestModel:
	//	{RestModel}
	//	'RestModel'
	//	name=EString
	//	'{' ('url' url=EString)? ('resources' '{' resources+=Resource ("," resources+=Resource)* '}')?
	//	'}';
	public RestModelElements getRestModelAccess() {
		return pRestModel;
	}
	
	public ParserRule getRestModelRule() {
		return getRestModelAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Resource:
	//	{Resource} put?='put'?
	//	post?='post'?
	//	delete?='delete'?
	//	get?='get'?
	//	'Resource'
	//	name=EString
	//	'{' ('entity' entity=EString)? ('reference' '(' reference+=[Resource|EString] ("," reference+=[Resource|EString])*
	//	')')? ('subresource' '{' subresource+=Resource ("," subresource+=Resource)* '}')?
	//	'}';
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
