<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="requirements" nsURI="http://www.example.org/requirements" nsPrefix="requirements">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MustHaveTitle TitleLengthMustBeGreaterOrEqualThanFive MustHaveDescription DescriptionLengthMustBeGreaterOrEqualThanTen StateCannotBeResolvedIfResolutionIsInvalid StateCannotBeApprovedIfResolutionIsInvalid StateCannotBeReviewedIfResolutionIsInvalid MustHaveCreationDate MustHaveAuthor AuthorLengthMustBeGreaterOrEqualThanThree"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="MustHaveTitle" value="not title.oclIsUndefined()"/>
      <details key="TitleLengthMustBeGreaterOrEqualThanFive" value="title.size() >= 5"/>
      <details key="MustHaveDescription" value="not description.oclIsUndefined()"/>
      <details key="DescriptionLengthMustBeGreaterOrEqualThanTen" value="description.size() >= 10"/>
      <details key="StateCannotBeResolvedIfResolutionIsInvalid" value="if resolution = 'INVALID' then &#xA;&#x9;&#x9;&#x9;&#x9;state &lt;> 'RESOLVED'&#xA;&#x9;&#x9;&#x9; else &#xA;&#x9;&#x9;&#x9; &#x9;true&#xA;&#x9;&#x9;&#x9; endif "/>
      <details key="StateCannotBeApprovedIfResolutionIsInvalid" value="if resolution = 'INVALID' then &#xA;&#x9;&#x9;&#x9;&#x9;state &lt;> 'APPROVED'&#xA;&#x9;&#x9;&#x9; else &#xA;&#x9;&#x9;&#x9; &#x9;true&#xA;&#x9;&#x9;&#x9; endif "/>
      <details key="StateCannotBeReviewedIfResolutionIsInvalid" value="if resolution = 'INVALID' then &#xA;&#x9;&#x9;&#x9;&#x9;state &lt;> 'REVIEWED'&#xA;&#x9;&#x9;&#x9; else &#xA;&#x9;&#x9;&#x9; &#x9;true&#xA;&#x9;&#x9;&#x9; endif "/>
      <details key="MustHaveCreationDate" value="not created.oclIsUndefined()"/>
      <details key="MustHaveAuthor" value="not author.oclIsUndefined()"/>
      <details key="AuthorLengthMustBeGreaterOrEqualThanThree" value="author.size() >= 3"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="#//Version" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type" defaultValueLiteral="FUNCTIONAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//Priority"
        defaultValueLiteral="HIGH"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"
        defaultValueLiteral="NEW"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="#//Resolution"
        defaultValueLiteral="INVALID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Requirement" containment="true" eOpposite="#//Requirement/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Requirement"
        eOpposite="#//Requirement/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MustHaveDescription DescriptionLengthMustBeGreaterOrEqualThanTen MustHaveName NameLengthMustBeGreaterOrEqualThanTen CannotHaveSubRequirementsGroupWithSameName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="MustHaveDescription" value="not description.oclIsUndefined()"/>
      <details key="DescriptionLengthMustBeGreaterOrEqualThanTen" value="description.size() >= 10"/>
      <details key="MustHaveName" value="not name.oclIsUndefined()"/>
      <details key="NameLengthMustBeGreaterOrEqualThanTen" value="name.size() >= 5"/>
      <details key="CannotHaveSubRequirementsGroupWithSameName" value="&#xA;&#x9;&#x9;if not parent.oclIsUndefined()&#xA;&#x9;&#x9;then &#xA;&#x9;&#x9;&#x9;not parent.name.equalsIgnoreCase(name)&#xA;&#x9;&#x9;else &#xA;&#x9;&#x9;&#x9;true&#xA;&#x9;&#x9;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//RequirementGroup" containment="true" eOpposite="#//RequirementGroup/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//RequirementGroup"
        eOpposite="#//RequirementGroup/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MustHaveTitle TitleLengthMustBeGreaterOrEqualThanThree"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="MustHaveTitle" value="not title.oclIsUndefined()"/>
      <details key="TitleLengthMustBeGreaterOrEqualThanThree" value="title.size() >= 3"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//RequirementGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MajorCannotBeLowerThanZero MinorCannotBeLowerThanZero ServiceCannotBeLowerThanZero"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="MajorCannotBeLowerThanZero" value="major >= 0"/>
      <details key="MinorCannotBeLowerThanZero" value="minor >= 0"/>
      <details key="ServiceCannotBeLowerThanZero" value="service >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MustHaveAuthor AuthorLengthMustBeGreaterOrEqualThanThree MustHaveBody BodyLengthMustBeGreaterOrEqualThanFifteen MustHaveSubject SubjectLengthMustBeGreaterOrEqualThanTen MustHaveCreationDate"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="MustHaveAuthor" value="not author.oclIsUndefined()"/>
      <details key="AuthorLengthMustBeGreaterOrEqualThanThree" value="author.size() >= 3"/>
      <details key="MustHaveBody" value="not body.oclIsUndefined()"/>
      <details key="BodyLengthMustBeGreaterOrEqualThanFifteen" value="body.size() >= 15"/>
      <details key="MustHaveSubject" value="not subject.oclIsUndefined()"/>
      <details key="SubjectLengthMustBeGreaterOrEqualThanTen" value="subject.size() >= 10"/>
      <details key="MustHaveCreationDate" value="not created.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Resolution">
    <eLiterals name="INVALID"/>
    <eLiterals name="ACCEPTED" value="1"/>
    <eLiterals name="IMPLEMENTED" value="2"/>
    <eLiterals name="LATER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="HIGH" value="2"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="LOW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="FUNCTIONAL"/>
    <eLiterals name="NONFUNCTIONAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="NEW"/>
    <eLiterals name="REVIEWED" value="1"/>
    <eLiterals name="APPROVED" value="2"/>
    <eLiterals name="RESOLVED" value="3"/>
  </eClassifiers>
</ecore:EPackage>
