/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c3.dsl.domain.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pt.isep.edom.project.c3.dsl.domain.parser.antlr.internal.InternalDomainParser;
import pt.isep.edom.project.c3.dsl.domain.services.DomainGrammarAccess;

public class DomainParser extends AbstractAntlrParser {

	@Inject
	private DomainGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDomainParser createParser(XtextTokenStream stream) {
		return new InternalDomainParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public DomainGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DomainGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
