/*
 * generated by Xtext 2.19.0
 */
package requirements.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_3_1_0 = (RuleCall)cTitleAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cGroupsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cGroupsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cGroupsRequirementGroupParserRuleCall_4_2_0 = (RuleCall)cGroupsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cGroupsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cGroupsRequirementGroupParserRuleCall_4_3_1_0 = (RuleCall)cGroupsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Model:
		//	{Model}
		//	'Model'
		//	'{' ('title' title=EString)? ('groups' '{' groups+=RequirementGroup ("," groups+=RequirementGroup)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Model} 'Model' '{' ('title' title=EString)? ('groups' '{' groups+=RequirementGroup ("," groups+=RequirementGroup)*
		//'}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }
		
		//'Model'
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('title' title=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'title'
		public Keyword getTitleKeyword_3_0() { return cTitleKeyword_3_0; }
		
		//title=EString
		public Assignment getTitleAssignment_3_1() { return cTitleAssignment_3_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_3_1_0() { return cTitleEStringParserRuleCall_3_1_0; }
		
		//('groups' '{' groups+=RequirementGroup ("," groups+=RequirementGroup)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'groups'
		public Keyword getGroupsKeyword_4_0() { return cGroupsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//groups+=RequirementGroup
		public Assignment getGroupsAssignment_4_2() { return cGroupsAssignment_4_2; }
		
		//RequirementGroup
		public RuleCall getGroupsRequirementGroupParserRuleCall_4_2_0() { return cGroupsRequirementGroupParserRuleCall_4_2_0; }
		
		//("," groups+=RequirementGroup)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//groups+=RequirementGroup
		public Assignment getGroupsAssignment_4_3_1() { return cGroupsAssignment_4_3_1; }
		
		//RequirementGroup
		public RuleCall getGroupsRequirementGroupParserRuleCall_4_3_1_0() { return cGroupsRequirementGroupParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class RequirementGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.RequirementGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequirementGroupAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequirementGroupKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIdAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_5_1_0 = (RuleCall)cIdAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRequirementsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRequirementsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRequirementsRequirementParserRuleCall_6_2_0 = (RuleCall)cRequirementsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRequirementsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRequirementsRequirementParserRuleCall_6_3_1_0 = (RuleCall)cRequirementsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cChildrenKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cChildrenAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cChildrenRequirementGroupParserRuleCall_7_2_0 = (RuleCall)cChildrenAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cChildrenAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cChildrenRequirementGroupParserRuleCall_7_3_1_0 = (RuleCall)cChildrenAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//RequirementGroup:
		//	{RequirementGroup}
		//	'RequirementGroup'
		//	name=EString
		//	'{' ('description' description=EString)? ('id' id=EString)? ('requirements' '{' requirements+=Requirement (","
		//	requirements+=Requirement)* '}')? ('children' '{' children+=RequirementGroup ("," children+=RequirementGroup)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RequirementGroup} 'RequirementGroup' name=EString '{' ('description' description=EString)? ('id' id=EString)?
		//('requirements' '{' requirements+=Requirement ("," requirements+=Requirement)* '}')? ('children' '{'
		//children+=RequirementGroup ("," children+=RequirementGroup)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{RequirementGroup}
		public Action getRequirementGroupAction_0() { return cRequirementGroupAction_0; }
		
		//'RequirementGroup'
		public Keyword getRequirementGroupKeyword_1() { return cRequirementGroupKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('id' id=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'id'
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }
		
		//id=EString
		public Assignment getIdAssignment_5_1() { return cIdAssignment_5_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_5_1_0() { return cIdEStringParserRuleCall_5_1_0; }
		
		//('requirements' '{' requirements+=Requirement ("," requirements+=Requirement)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'requirements'
		public Keyword getRequirementsKeyword_6_0() { return cRequirementsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//requirements+=Requirement
		public Assignment getRequirementsAssignment_6_2() { return cRequirementsAssignment_6_2; }
		
		//Requirement
		public RuleCall getRequirementsRequirementParserRuleCall_6_2_0() { return cRequirementsRequirementParserRuleCall_6_2_0; }
		
		//("," requirements+=Requirement)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//requirements+=Requirement
		public Assignment getRequirementsAssignment_6_3_1() { return cRequirementsAssignment_6_3_1; }
		
		//Requirement
		public RuleCall getRequirementsRequirementParserRuleCall_6_3_1_0() { return cRequirementsRequirementParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('children' '{' children+=RequirementGroup ("," children+=RequirementGroup)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'children'
		public Keyword getChildrenKeyword_7_0() { return cChildrenKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//children+=RequirementGroup
		public Assignment getChildrenAssignment_7_2() { return cChildrenAssignment_7_2; }
		
		//RequirementGroup
		public RuleCall getChildrenRequirementGroupParserRuleCall_7_2_0() { return cChildrenRequirementGroupParserRuleCall_7_2_0; }
		
		//("," children+=RequirementGroup)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//children+=RequirementGroup
		public Assignment getChildrenAssignment_7_3_1() { return cChildrenAssignment_7_3_1; }
		
		//RequirementGroup
		public RuleCall getChildrenRequirementGroupParserRuleCall_7_3_1_0() { return cChildrenRequirementGroupParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class RequirementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.Requirement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRequirementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRequirementKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTypeTypeEnumRuleCall_5_1_0 = (RuleCall)cTypeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPriorityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPriorityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPriorityPriorityEnumRuleCall_6_1_0 = (RuleCall)cPriorityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAuthorKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAuthorAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_7_1_0 = (RuleCall)cAuthorAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCreatedKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cCreatedAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cCreatedEDateParserRuleCall_8_1_0 = (RuleCall)cCreatedAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cIdKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cIdAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_9_1_0 = (RuleCall)cIdAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cStateKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cStateAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cStateStateEnumRuleCall_10_1_0 = (RuleCall)cStateAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cResolutionKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cResolutionAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cResolutionResolutionEnumRuleCall_11_1_0 = (RuleCall)cResolutionAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cDependenciesKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cDependenciesAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final CrossReference cDependenciesRequirementCrossReference_12_2_0 = (CrossReference)cDependenciesAssignment_12_2.eContents().get(0);
		private final RuleCall cDependenciesRequirementEStringParserRuleCall_12_2_0_1 = (RuleCall)cDependenciesRequirementCrossReference_12_2_0.eContents().get(1);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cDependenciesAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final CrossReference cDependenciesRequirementCrossReference_12_3_1_0 = (CrossReference)cDependenciesAssignment_12_3_1.eContents().get(0);
		private final RuleCall cDependenciesRequirementEStringParserRuleCall_12_3_1_0_1 = (RuleCall)cDependenciesRequirementCrossReference_12_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Keyword cVersionKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cVersionAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cVersionVersionParserRuleCall_14_0 = (RuleCall)cVersionAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommentsKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cCommentsAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final RuleCall cCommentsCommentParserRuleCall_15_2_0 = (RuleCall)cCommentsAssignment_15_2.eContents().get(0);
		private final Group cGroup_15_3 = (Group)cGroup_15.eContents().get(3);
		private final Keyword cCommaKeyword_15_3_0 = (Keyword)cGroup_15_3.eContents().get(0);
		private final Assignment cCommentsAssignment_15_3_1 = (Assignment)cGroup_15_3.eContents().get(1);
		private final RuleCall cCommentsCommentParserRuleCall_15_3_1_0 = (RuleCall)cCommentsAssignment_15_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15_4 = (Keyword)cGroup_15.eContents().get(4);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cChildrenKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_16_1 = (Keyword)cGroup_16.eContents().get(1);
		private final Assignment cChildrenAssignment_16_2 = (Assignment)cGroup_16.eContents().get(2);
		private final RuleCall cChildrenRequirementParserRuleCall_16_2_0 = (RuleCall)cChildrenAssignment_16_2.eContents().get(0);
		private final Group cGroup_16_3 = (Group)cGroup_16.eContents().get(3);
		private final Keyword cCommaKeyword_16_3_0 = (Keyword)cGroup_16_3.eContents().get(0);
		private final Assignment cChildrenAssignment_16_3_1 = (Assignment)cGroup_16_3.eContents().get(1);
		private final RuleCall cChildrenRequirementParserRuleCall_16_3_1_0 = (RuleCall)cChildrenAssignment_16_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16_4 = (Keyword)cGroup_16.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//Requirement:
		//	{Requirement}
		//	'Requirement'
		//	name=EString
		//	'{' ('description' description=EString)? ('type' type=Type)? ('priority' priority=Priority)? ('author'
		//	author=EString)? ('created' created=EDate)? ('id' id=EString)? ('state' state=State)? ('resolution'
		//	resolution=Resolution)? ('dependencies' '(' dependencies+=[Requirement|EString] (","
		//	dependencies+=[Requirement|EString])* ')')?
		//	'version' version=Version ('comments' '{' comments+=Comment ("," comments+=Comment)* '}')? ('children' '{'
		//	children+=Requirement ("," children+=Requirement)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Requirement} 'Requirement' name=EString '{' ('description' description=EString)? ('type' type=Type)? ('priority'
		//priority=Priority)? ('author' author=EString)? ('created' created=EDate)? ('id' id=EString)? ('state' state=State)?
		//('resolution' resolution=Resolution)? ('dependencies' '(' dependencies+=[Requirement|EString] (","
		//dependencies+=[Requirement|EString])* ')')? 'version' version=Version ('comments' '{' comments+=Comment (","
		//comments+=Comment)* '}')? ('children' '{' children+=Requirement ("," children+=Requirement)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Requirement}
		public Action getRequirementAction_0() { return cRequirementAction_0; }
		
		//'Requirement'
		public Keyword getRequirementKeyword_1() { return cRequirementKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('type' type=Type)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'type'
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }
		
		//type=Type
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_5_1_0() { return cTypeTypeEnumRuleCall_5_1_0; }
		
		//('priority' priority=Priority)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'priority'
		public Keyword getPriorityKeyword_6_0() { return cPriorityKeyword_6_0; }
		
		//priority=Priority
		public Assignment getPriorityAssignment_6_1() { return cPriorityAssignment_6_1; }
		
		//Priority
		public RuleCall getPriorityPriorityEnumRuleCall_6_1_0() { return cPriorityPriorityEnumRuleCall_6_1_0; }
		
		//('author' author=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'author'
		public Keyword getAuthorKeyword_7_0() { return cAuthorKeyword_7_0; }
		
		//author=EString
		public Assignment getAuthorAssignment_7_1() { return cAuthorAssignment_7_1; }
		
		//EString
		public RuleCall getAuthorEStringParserRuleCall_7_1_0() { return cAuthorEStringParserRuleCall_7_1_0; }
		
		//('created' created=EDate)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'created'
		public Keyword getCreatedKeyword_8_0() { return cCreatedKeyword_8_0; }
		
		//created=EDate
		public Assignment getCreatedAssignment_8_1() { return cCreatedAssignment_8_1; }
		
		//EDate
		public RuleCall getCreatedEDateParserRuleCall_8_1_0() { return cCreatedEDateParserRuleCall_8_1_0; }
		
		//('id' id=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'id'
		public Keyword getIdKeyword_9_0() { return cIdKeyword_9_0; }
		
		//id=EString
		public Assignment getIdAssignment_9_1() { return cIdAssignment_9_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_9_1_0() { return cIdEStringParserRuleCall_9_1_0; }
		
		//('state' state=State)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'state'
		public Keyword getStateKeyword_10_0() { return cStateKeyword_10_0; }
		
		//state=State
		public Assignment getStateAssignment_10_1() { return cStateAssignment_10_1; }
		
		//State
		public RuleCall getStateStateEnumRuleCall_10_1_0() { return cStateStateEnumRuleCall_10_1_0; }
		
		//('resolution' resolution=Resolution)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'resolution'
		public Keyword getResolutionKeyword_11_0() { return cResolutionKeyword_11_0; }
		
		//resolution=Resolution
		public Assignment getResolutionAssignment_11_1() { return cResolutionAssignment_11_1; }
		
		//Resolution
		public RuleCall getResolutionResolutionEnumRuleCall_11_1_0() { return cResolutionResolutionEnumRuleCall_11_1_0; }
		
		//('dependencies' '(' dependencies+=[Requirement|EString] ("," dependencies+=[Requirement|EString])* ')')?
		public Group getGroup_12() { return cGroup_12; }
		
		//'dependencies'
		public Keyword getDependenciesKeyword_12_0() { return cDependenciesKeyword_12_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_12_1() { return cLeftParenthesisKeyword_12_1; }
		
		//dependencies+=[Requirement|EString]
		public Assignment getDependenciesAssignment_12_2() { return cDependenciesAssignment_12_2; }
		
		//[Requirement|EString]
		public CrossReference getDependenciesRequirementCrossReference_12_2_0() { return cDependenciesRequirementCrossReference_12_2_0; }
		
		//EString
		public RuleCall getDependenciesRequirementEStringParserRuleCall_12_2_0_1() { return cDependenciesRequirementEStringParserRuleCall_12_2_0_1; }
		
		//("," dependencies+=[Requirement|EString])*
		public Group getGroup_12_3() { return cGroup_12_3; }
		
		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }
		
		//dependencies+=[Requirement|EString]
		public Assignment getDependenciesAssignment_12_3_1() { return cDependenciesAssignment_12_3_1; }
		
		//[Requirement|EString]
		public CrossReference getDependenciesRequirementCrossReference_12_3_1_0() { return cDependenciesRequirementCrossReference_12_3_1_0; }
		
		//EString
		public RuleCall getDependenciesRequirementEStringParserRuleCall_12_3_1_0_1() { return cDependenciesRequirementEStringParserRuleCall_12_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_12_4() { return cRightParenthesisKeyword_12_4; }
		
		//'version'
		public Keyword getVersionKeyword_13() { return cVersionKeyword_13; }
		
		//version=Version
		public Assignment getVersionAssignment_14() { return cVersionAssignment_14; }
		
		//Version
		public RuleCall getVersionVersionParserRuleCall_14_0() { return cVersionVersionParserRuleCall_14_0; }
		
		//('comments' '{' comments+=Comment ("," comments+=Comment)* '}')?
		public Group getGroup_15() { return cGroup_15; }
		
		//'comments'
		public Keyword getCommentsKeyword_15_0() { return cCommentsKeyword_15_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_15_1() { return cLeftCurlyBracketKeyword_15_1; }
		
		//comments+=Comment
		public Assignment getCommentsAssignment_15_2() { return cCommentsAssignment_15_2; }
		
		//Comment
		public RuleCall getCommentsCommentParserRuleCall_15_2_0() { return cCommentsCommentParserRuleCall_15_2_0; }
		
		//("," comments+=Comment)*
		public Group getGroup_15_3() { return cGroup_15_3; }
		
		//","
		public Keyword getCommaKeyword_15_3_0() { return cCommaKeyword_15_3_0; }
		
		//comments+=Comment
		public Assignment getCommentsAssignment_15_3_1() { return cCommentsAssignment_15_3_1; }
		
		//Comment
		public RuleCall getCommentsCommentParserRuleCall_15_3_1_0() { return cCommentsCommentParserRuleCall_15_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15_4() { return cRightCurlyBracketKeyword_15_4; }
		
		//('children' '{' children+=Requirement ("," children+=Requirement)* '}')?
		public Group getGroup_16() { return cGroup_16; }
		
		//'children'
		public Keyword getChildrenKeyword_16_0() { return cChildrenKeyword_16_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_16_1() { return cLeftCurlyBracketKeyword_16_1; }
		
		//children+=Requirement
		public Assignment getChildrenAssignment_16_2() { return cChildrenAssignment_16_2; }
		
		//Requirement
		public RuleCall getChildrenRequirementParserRuleCall_16_2_0() { return cChildrenRequirementParserRuleCall_16_2_0; }
		
		//("," children+=Requirement)*
		public Group getGroup_16_3() { return cGroup_16_3; }
		
		//","
		public Keyword getCommaKeyword_16_3_0() { return cCommaKeyword_16_3_0; }
		
		//children+=Requirement
		public Assignment getChildrenAssignment_16_3_1() { return cChildrenAssignment_16_3_1; }
		
		//Requirement
		public RuleCall getChildrenRequirementParserRuleCall_16_3_1_0() { return cChildrenRequirementParserRuleCall_16_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16_4() { return cRightCurlyBracketKeyword_16_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class VersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.Version");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVersionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMajorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMajorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMajorEIntParserRuleCall_3_0 = (RuleCall)cMajorAssignment_3.eContents().get(0);
		private final Keyword cMinorKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMinorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMinorEIntParserRuleCall_5_0 = (RuleCall)cMinorAssignment_5.eContents().get(0);
		private final Keyword cServiceKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cServiceAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cServiceEIntParserRuleCall_7_0 = (RuleCall)cServiceAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Version:
		//	'Version'
		//	'{'
		//	'major' major=EInt
		//	'minor' minor=EInt
		//	'service' service=EInt
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Version' '{' 'major' major=EInt 'minor' minor=EInt 'service' service=EInt '}'
		public Group getGroup() { return cGroup; }
		
		//'Version'
		public Keyword getVersionKeyword_0() { return cVersionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'major'
		public Keyword getMajorKeyword_2() { return cMajorKeyword_2; }
		
		//major=EInt
		public Assignment getMajorAssignment_3() { return cMajorAssignment_3; }
		
		//EInt
		public RuleCall getMajorEIntParserRuleCall_3_0() { return cMajorEIntParserRuleCall_3_0; }
		
		//'minor'
		public Keyword getMinorKeyword_4() { return cMinorKeyword_4; }
		
		//minor=EInt
		public Assignment getMinorAssignment_5() { return cMinorAssignment_5; }
		
		//EInt
		public RuleCall getMinorEIntParserRuleCall_5_0() { return cMinorEIntParserRuleCall_5_0; }
		
		//'service'
		public Keyword getServiceKeyword_6() { return cServiceKeyword_6; }
		
		//service=EInt
		public Assignment getServiceAssignment_7() { return cServiceAssignment_7; }
		
		//EInt
		public RuleCall getServiceEIntParserRuleCall_7_0() { return cServiceEIntParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class CommentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.Comment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCommentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCommentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSubjectKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSubjectAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cSubjectEStringParserRuleCall_3_1_0 = (RuleCall)cSubjectAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBodyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBodyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cBodyEStringParserRuleCall_4_1_0 = (RuleCall)cBodyAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAuthorKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAuthorAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_5_1_0 = (RuleCall)cAuthorAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCreatedKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCreatedAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCreatedEDateParserRuleCall_6_1_0 = (RuleCall)cCreatedAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cChildrenKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cChildrenAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cChildrenCommentParserRuleCall_7_2_0 = (RuleCall)cChildrenAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cChildrenAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cChildrenCommentParserRuleCall_7_3_1_0 = (RuleCall)cChildrenAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Comment:
		//	{Comment}
		//	'Comment'
		//	'{' ('subject' subject=EString)? ('body' body=EString)? ('author' author=EString)? ('created' created=EDate)?
		//	('children' '{' children+=Comment ("," children+=Comment)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Comment} 'Comment' '{' ('subject' subject=EString)? ('body' body=EString)? ('author' author=EString)? ('created'
		//created=EDate)? ('children' '{' children+=Comment ("," children+=Comment)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Comment}
		public Action getCommentAction_0() { return cCommentAction_0; }
		
		//'Comment'
		public Keyword getCommentKeyword_1() { return cCommentKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('subject' subject=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'subject'
		public Keyword getSubjectKeyword_3_0() { return cSubjectKeyword_3_0; }
		
		//subject=EString
		public Assignment getSubjectAssignment_3_1() { return cSubjectAssignment_3_1; }
		
		//EString
		public RuleCall getSubjectEStringParserRuleCall_3_1_0() { return cSubjectEStringParserRuleCall_3_1_0; }
		
		//('body' body=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'body'
		public Keyword getBodyKeyword_4_0() { return cBodyKeyword_4_0; }
		
		//body=EString
		public Assignment getBodyAssignment_4_1() { return cBodyAssignment_4_1; }
		
		//EString
		public RuleCall getBodyEStringParserRuleCall_4_1_0() { return cBodyEStringParserRuleCall_4_1_0; }
		
		//('author' author=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'author'
		public Keyword getAuthorKeyword_5_0() { return cAuthorKeyword_5_0; }
		
		//author=EString
		public Assignment getAuthorAssignment_5_1() { return cAuthorAssignment_5_1; }
		
		//EString
		public RuleCall getAuthorEStringParserRuleCall_5_1_0() { return cAuthorEStringParserRuleCall_5_1_0; }
		
		//('created' created=EDate)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'created'
		public Keyword getCreatedKeyword_6_0() { return cCreatedKeyword_6_0; }
		
		//created=EDate
		public Assignment getCreatedAssignment_6_1() { return cCreatedAssignment_6_1; }
		
		//EDate
		public RuleCall getCreatedEDateParserRuleCall_6_1_0() { return cCreatedEDateParserRuleCall_6_1_0; }
		
		//('children' '{' children+=Comment ("," children+=Comment)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'children'
		public Keyword getChildrenKeyword_7_0() { return cChildrenKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//children+=Comment
		public Assignment getChildrenAssignment_7_2() { return cChildrenAssignment_7_2; }
		
		//Comment
		public RuleCall getChildrenCommentParserRuleCall_7_2_0() { return cChildrenCommentParserRuleCall_7_2_0; }
		
		//("," children+=Comment)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//children+=Comment
		public Assignment getChildrenAssignment_7_3_1() { return cChildrenAssignment_7_3_1; }
		
		//Comment
		public RuleCall getChildrenCommentParserRuleCall_7_3_1_0() { return cChildrenCommentParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.EDate");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCUSTOM_DATE_SINGLE_QUOTETerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCUSTOM_DATE_DOUBLE_QUOTETerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EDate ecore::EDate:
		//	CUSTOM_DATE_SINGLE_QUOTE | CUSTOM_DATE_DOUBLE_QUOTE
		//	/* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//CUSTOM_DATE_SINGLE_QUOTE | CUSTOM_DATE_DOUBLE_QUOTE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CUSTOM_DATE_SINGLE_QUOTE
		public RuleCall getCUSTOM_DATE_SINGLE_QUOTETerminalRuleCall_0() { return cCUSTOM_DATE_SINGLE_QUOTETerminalRuleCall_0; }
		
		//CUSTOM_DATE_DOUBLE_QUOTE
		public RuleCall getCUSTOM_DATE_DOUBLE_QUOTETerminalRuleCall_1() { return cCUSTOM_DATE_DOUBLE_QUOTETerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class TypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFUNCTIONALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFUNCTIONALFUNCTIONALKeyword_0_0 = (Keyword)cFUNCTIONALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNONFUNCTIONALEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNONFUNCTIONALNONFUNCTIONALKeyword_1_0 = (Keyword)cNONFUNCTIONALEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Type:
		//	FUNCTIONAL | NONFUNCTIONAL;
		public EnumRule getRule() { return rule; }
		
		//FUNCTIONAL | NONFUNCTIONAL
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FUNCTIONAL
		public EnumLiteralDeclaration getFUNCTIONALEnumLiteralDeclaration_0() { return cFUNCTIONALEnumLiteralDeclaration_0; }
		
		//'FUNCTIONAL'
		public Keyword getFUNCTIONALFUNCTIONALKeyword_0_0() { return cFUNCTIONALFUNCTIONALKeyword_0_0; }
		
		//NONFUNCTIONAL
		public EnumLiteralDeclaration getNONFUNCTIONALEnumLiteralDeclaration_1() { return cNONFUNCTIONALEnumLiteralDeclaration_1; }
		
		//'NONFUNCTIONAL'
		public Keyword getNONFUNCTIONALNONFUNCTIONALKeyword_1_0() { return cNONFUNCTIONALNONFUNCTIONALKeyword_1_0; }
	}
	public class PriorityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.Priority");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHIGHEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHIGHHIGHKeyword_0_0 = (Keyword)cHIGHEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMEDIUMEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMEDIUMMEDIUMKeyword_1_0 = (Keyword)cMEDIUMEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLOWEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLOWLOWKeyword_2_0 = (Keyword)cLOWEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Priority:
		//	HIGH | MEDIUM | LOW;
		public EnumRule getRule() { return rule; }
		
		//HIGH | MEDIUM | LOW
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//HIGH
		public EnumLiteralDeclaration getHIGHEnumLiteralDeclaration_0() { return cHIGHEnumLiteralDeclaration_0; }
		
		//'HIGH'
		public Keyword getHIGHHIGHKeyword_0_0() { return cHIGHHIGHKeyword_0_0; }
		
		//MEDIUM
		public EnumLiteralDeclaration getMEDIUMEnumLiteralDeclaration_1() { return cMEDIUMEnumLiteralDeclaration_1; }
		
		//'MEDIUM'
		public Keyword getMEDIUMMEDIUMKeyword_1_0() { return cMEDIUMMEDIUMKeyword_1_0; }
		
		//LOW
		public EnumLiteralDeclaration getLOWEnumLiteralDeclaration_2() { return cLOWEnumLiteralDeclaration_2; }
		
		//'LOW'
		public Keyword getLOWLOWKeyword_2_0() { return cLOWLOWKeyword_2_0; }
	}
	public class StateElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.State");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNEWEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNEWNEWKeyword_0_0 = (Keyword)cNEWEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cREVIEWEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cREVIEWEDREVIEWEDKeyword_1_0 = (Keyword)cREVIEWEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAPPROVEDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAPPROVEDAPPROVEDKeyword_2_0 = (Keyword)cAPPROVEDEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cRESOLVEDEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cRESOLVEDRESOLVEDKeyword_3_0 = (Keyword)cRESOLVEDEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum State:
		//	NEW | REVIEWED | APPROVED | RESOLVED;
		public EnumRule getRule() { return rule; }
		
		//NEW | REVIEWED | APPROVED | RESOLVED
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NEW
		public EnumLiteralDeclaration getNEWEnumLiteralDeclaration_0() { return cNEWEnumLiteralDeclaration_0; }
		
		//'NEW'
		public Keyword getNEWNEWKeyword_0_0() { return cNEWNEWKeyword_0_0; }
		
		//REVIEWED
		public EnumLiteralDeclaration getREVIEWEDEnumLiteralDeclaration_1() { return cREVIEWEDEnumLiteralDeclaration_1; }
		
		//'REVIEWED'
		public Keyword getREVIEWEDREVIEWEDKeyword_1_0() { return cREVIEWEDREVIEWEDKeyword_1_0; }
		
		//APPROVED
		public EnumLiteralDeclaration getAPPROVEDEnumLiteralDeclaration_2() { return cAPPROVEDEnumLiteralDeclaration_2; }
		
		//'APPROVED'
		public Keyword getAPPROVEDAPPROVEDKeyword_2_0() { return cAPPROVEDAPPROVEDKeyword_2_0; }
		
		//RESOLVED
		public EnumLiteralDeclaration getRESOLVEDEnumLiteralDeclaration_3() { return cRESOLVEDEnumLiteralDeclaration_3; }
		
		//'RESOLVED'
		public Keyword getRESOLVEDRESOLVEDKeyword_3_0() { return cRESOLVEDRESOLVEDKeyword_3_0; }
	}
	public class ResolutionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.Resolution");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINVALIDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINVALIDINVALIDKeyword_0_0 = (Keyword)cINVALIDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cACCEPTEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cACCEPTEDACCEPTEDKeyword_1_0 = (Keyword)cACCEPTEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cIMPLEMENTEDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cIMPLEMENTEDIMPLEMENTEDKeyword_2_0 = (Keyword)cIMPLEMENTEDEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLATEREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLATERLATERKeyword_3_0 = (Keyword)cLATEREnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Resolution:
		//	INVALID | ACCEPTED | IMPLEMENTED | LATER;
		public EnumRule getRule() { return rule; }
		
		//INVALID | ACCEPTED | IMPLEMENTED | LATER
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INVALID
		public EnumLiteralDeclaration getINVALIDEnumLiteralDeclaration_0() { return cINVALIDEnumLiteralDeclaration_0; }
		
		//'INVALID'
		public Keyword getINVALIDINVALIDKeyword_0_0() { return cINVALIDINVALIDKeyword_0_0; }
		
		//ACCEPTED
		public EnumLiteralDeclaration getACCEPTEDEnumLiteralDeclaration_1() { return cACCEPTEDEnumLiteralDeclaration_1; }
		
		//'ACCEPTED'
		public Keyword getACCEPTEDACCEPTEDKeyword_1_0() { return cACCEPTEDACCEPTEDKeyword_1_0; }
		
		//IMPLEMENTED
		public EnumLiteralDeclaration getIMPLEMENTEDEnumLiteralDeclaration_2() { return cIMPLEMENTEDEnumLiteralDeclaration_2; }
		
		//'IMPLEMENTED'
		public Keyword getIMPLEMENTEDIMPLEMENTEDKeyword_2_0() { return cIMPLEMENTEDIMPLEMENTEDKeyword_2_0; }
		
		//LATER
		public EnumLiteralDeclaration getLATEREnumLiteralDeclaration_3() { return cLATEREnumLiteralDeclaration_3; }
		
		//'LATER'
		public Keyword getLATERLATERKeyword_3_0() { return cLATERLATERKeyword_3_0; }
	}
	
	private final ModelElements pModel;
	private final RequirementGroupElements pRequirementGroup;
	private final EStringElements pEString;
	private final RequirementElements pRequirement;
	private final VersionElements pVersion;
	private final CommentElements pComment;
	private final TypeElements eType;
	private final PriorityElements ePriority;
	private final TerminalRule tCUSTOM_DATE_SINGLE_QUOTE;
	private final TerminalRule tCUSTOM_DATE_DOUBLE_QUOTE;
	private final EDateElements pEDate;
	private final StateElements eState;
	private final ResolutionElements eResolution;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pRequirementGroup = new RequirementGroupElements();
		this.pEString = new EStringElements();
		this.pRequirement = new RequirementElements();
		this.pVersion = new VersionElements();
		this.pComment = new CommentElements();
		this.eType = new TypeElements();
		this.ePriority = new PriorityElements();
		this.tCUSTOM_DATE_SINGLE_QUOTE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.CUSTOM_DATE_SINGLE_QUOTE");
		this.tCUSTOM_DATE_DOUBLE_QUOTE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "requirements.dsl.RDSL.CUSTOM_DATE_DOUBLE_QUOTE");
		this.pEDate = new EDateElements();
		this.eState = new StateElements();
		this.eResolution = new ResolutionElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("requirements.dsl.RDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	{Model}
	//	'Model'
	//	'{' ('title' title=EString)? ('groups' '{' groups+=RequirementGroup ("," groups+=RequirementGroup)* '}')?
	//	'}';
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//RequirementGroup:
	//	{RequirementGroup}
	//	'RequirementGroup'
	//	name=EString
	//	'{' ('description' description=EString)? ('id' id=EString)? ('requirements' '{' requirements+=Requirement (","
	//	requirements+=Requirement)* '}')? ('children' '{' children+=RequirementGroup ("," children+=RequirementGroup)* '}')?
	//	'}';
	public RequirementGroupElements getRequirementGroupAccess() {
		return pRequirementGroup;
	}
	
	public ParserRule getRequirementGroupRule() {
		return getRequirementGroupAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Requirement:
	//	{Requirement}
	//	'Requirement'
	//	name=EString
	//	'{' ('description' description=EString)? ('type' type=Type)? ('priority' priority=Priority)? ('author'
	//	author=EString)? ('created' created=EDate)? ('id' id=EString)? ('state' state=State)? ('resolution'
	//	resolution=Resolution)? ('dependencies' '(' dependencies+=[Requirement|EString] (","
	//	dependencies+=[Requirement|EString])* ')')?
	//	'version' version=Version ('comments' '{' comments+=Comment ("," comments+=Comment)* '}')? ('children' '{'
	//	children+=Requirement ("," children+=Requirement)* '}')?
	//	'}';
	public RequirementElements getRequirementAccess() {
		return pRequirement;
	}
	
	public ParserRule getRequirementRule() {
		return getRequirementAccess().getRule();
	}
	
	//Version:
	//	'Version'
	//	'{'
	//	'major' major=EInt
	//	'minor' minor=EInt
	//	'service' service=EInt
	//	'}';
	public VersionElements getVersionAccess() {
		return pVersion;
	}
	
	public ParserRule getVersionRule() {
		return getVersionAccess().getRule();
	}
	
	//Comment:
	//	{Comment}
	//	'Comment'
	//	'{' ('subject' subject=EString)? ('body' body=EString)? ('author' author=EString)? ('created' created=EDate)?
	//	('children' '{' children+=Comment ("," children+=Comment)* '}')?
	//	'}';
	public CommentElements getCommentAccess() {
		return pComment;
	}
	
	public ParserRule getCommentRule() {
		return getCommentAccess().getRule();
	}
	
	//enum Type:
	//	FUNCTIONAL | NONFUNCTIONAL;
	public TypeElements getTypeAccess() {
		return eType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//enum Priority:
	//	HIGH | MEDIUM | LOW;
	public PriorityElements getPriorityAccess() {
		return ePriority;
	}
	
	public EnumRule getPriorityRule() {
		return getPriorityAccess().getRule();
	}
	
	//terminal CUSTOM_DATE_SINGLE_QUOTE:
	//	'\''? ('0'..'9'+ '-' '0'..'9'+ '-' '0'..'9'+) ('T' '0'..'9'+ ':' '0'..'9'+ ':' '0'..'9'+ ('.' '0'..'9'+ '+'
	//	'0'..'9'+)?)? '\''?;
	public TerminalRule getCUSTOM_DATE_SINGLE_QUOTERule() {
		return tCUSTOM_DATE_SINGLE_QUOTE;
	}
	
	//terminal CUSTOM_DATE_DOUBLE_QUOTE:
	//	'"'? ('0'..'9'+ '-' '0'..'9'+ '-' '0'..'9'+) ('T' '0'..'9'+ ':' '0'..'9'+ ':' '0'..'9'+ ('.' '0'..'9'+ '+'
	//	'0'..'9'+)?)? '"'?;
	public TerminalRule getCUSTOM_DATE_DOUBLE_QUOTERule() {
		return tCUSTOM_DATE_DOUBLE_QUOTE;
	}
	
	//EDate ecore::EDate:
	//	CUSTOM_DATE_SINGLE_QUOTE | CUSTOM_DATE_DOUBLE_QUOTE
	//	/* TODO: implement this rule and an appropriate IValueConverter */;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//enum State:
	//	NEW | REVIEWED | APPROVED | RESOLVED;
	public StateElements getStateAccess() {
		return eState;
	}
	
	public EnumRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//enum Resolution:
	//	INVALID | ACCEPTED | IMPLEMENTED | LATER;
	public ResolutionElements getResolutionAccess() {
		return eResolution;
	}
	
	public EnumRule getResolutionRule() {
		return getResolutionAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
