/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.project.c0.dsl.usecase.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class UseCaseUiModule extends AbstractUseCaseUiModule {
}
