/**
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.ide;

import pt.isep.edom.ide.AbstractRequirementsDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RequirementsDslIdeModule extends AbstractRequirementsDslIdeModule {
}
