<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gorgeousFood_Increment1" nsURI="http://www.example.org/gorgeousFood_Increment1"
    nsPrefix="gorgeousFood_Increment1">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveTitle titleMustHaveAtLeastFiveChars"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveTitle" value="not title.oclIsUndefined()"/>
      <details key="titleMustHaveAtLeastFiveChars" value="title.size() >= 5"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//RequirementGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveName nameMustHaveAtLeastFiveChars mustHaveDescription descriptionMustHaveAtLeastTenChars"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveName" value="not name.oclIsUndefined()"/>
      <details key="nameMustHaveAtLeastFiveChars" value="name.size() >= 5"/>
      <details key="mustHaveDescription" value="not description.oclIsUndefined()"/>
      <details key="descriptionMustHaveAtLeastTenChars" value="description.size() > 5"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//RequirementGroup" containment="true" eOpposite="#//RequirementGroup/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//RequirementGroup"
        eOpposite="#//RequirementGroup/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveTitle titleMustHaveAtLeastFiveChars mustHaveDescription descriptionMustHaveAtLeastTenChars mustHaveCreateDate commentsCreateDateMustBeAfterRequirementCreateDate"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveTitle" value="not title.oclIsUndefined()"/>
      <details key="titleMustHaveAtLeastFiveChars" value="title.size() >= 5"/>
      <details key="mustHaveDescription" value="not description.oclIsUndefined()"/>
      <details key="descriptionMustHaveAtLeastTenChars" value="description.size() >= 10"/>
      <details key="mustHaveCreateDate" value="not created.oclIsUndefined()"/>
      <details key="commentsCreateDateMustBeAfterRequirementCreateDate" value="self.comment->forAll(comment | comment.created >= self.created)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//Priority"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="#//Resolution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Requirement" containment="true" eOpposite="#//Requirement/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Requirement"
        eOpposite="#//Requirement/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
        eType="#//Version" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Resolution">
    <eLiterals name="INVALID"/>
    <eLiterals name="ACCEPTED" value="1"/>
    <eLiterals name="IMPLEMENTED" value="2"/>
    <eLiterals name="LATER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="HIGH"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="LOW" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="FUNCTIONAL"/>
    <eLiterals name="NONFUNCTIONAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="NEW"/>
    <eLiterals name="REVIEWED" value="1"/>
    <eLiterals name="APPROVED" value="2"/>
    <eLiterals name="RESOLVED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustHaveSubject subjectMustHaveAtLeastFiveChars mustHaveBody bodyMustHaveAtLeastFiveChars mustHaveAuthor mustHaveCreatedDate"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustHaveSubject" value="not subject.oclIsUndefined()"/>
      <details key="subjectMustHaveAtLeastFiveChars" value="subject.size() >= 5"/>
      <details key="mustHaveBody" value="not body.oclIsUndefined()"/>
      <details key="bodyMustHaveAtLeastFiveChars" value="body.size() >= 5"/>
      <details key="mustHaveAuthor" value="not author.oclIsUndefined()"/>
      <details key="mustHaveCreatedDate" value="not created.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
