/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import mindmap.mmapdsl.ui.internal.MmapdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MmapdslActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
