/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pt.isep.edom.parser.antlr.internal.InternalRequirementsDslParser;
import pt.isep.edom.services.RequirementsDslGrammarAccess;

public class RequirementsDslParser extends AbstractAntlrParser {

	@Inject
	private RequirementsDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRequirementsDslParser createParser(XtextTokenStream stream) {
		return new InternalRequirementsDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RequirementsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RequirementsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
