/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.edom.ide.contentassist.antlr.internal.InternalRequirementsDslParser;
import pt.isep.edom.services.RequirementsDslGrammarAccess;

public class RequirementsDslParser extends AbstractContentAssistParser {

	@Inject
	private RequirementsDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRequirementsDslParser createParser() {
		InternalRequirementsDslParser result = new InternalRequirementsDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getPriorityAccess().getAlternatives(), "rule__Priority__Alternatives");
					put(grammarAccess.getStateAccess().getAlternatives(), "rule__State__Alternatives");
					put(grammarAccess.getResolutionAccess().getAlternatives(), "rule__Resolution__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_3(), "rule__Model__Group_3__0");
					put(grammarAccess.getModelAccess().getGroup_4(), "rule__Model__Group_4__0");
					put(grammarAccess.getModelAccess().getGroup_4_3(), "rule__Model__Group_4_3__0");
					put(grammarAccess.getRequirementGroupAccess().getGroup(), "rule__RequirementGroup__Group__0");
					put(grammarAccess.getRequirementGroupAccess().getGroup_4(), "rule__RequirementGroup__Group_4__0");
					put(grammarAccess.getRequirementGroupAccess().getGroup_5(), "rule__RequirementGroup__Group_5__0");
					put(grammarAccess.getRequirementGroupAccess().getGroup_6(), "rule__RequirementGroup__Group_6__0");
					put(grammarAccess.getRequirementGroupAccess().getGroup_6_3(), "rule__RequirementGroup__Group_6_3__0");
					put(grammarAccess.getRequirementGroupAccess().getGroup_7(), "rule__RequirementGroup__Group_7__0");
					put(grammarAccess.getRequirementGroupAccess().getGroup_7_3(), "rule__RequirementGroup__Group_7_3__0");
					put(grammarAccess.getRequirementAccess().getGroup(), "rule__Requirement__Group__0");
					put(grammarAccess.getRequirementAccess().getGroup_2(), "rule__Requirement__Group_2__0");
					put(grammarAccess.getRequirementAccess().getGroup_3(), "rule__Requirement__Group_3__0");
					put(grammarAccess.getRequirementAccess().getGroup_4(), "rule__Requirement__Group_4__0");
					put(grammarAccess.getRequirementAccess().getGroup_5(), "rule__Requirement__Group_5__0");
					put(grammarAccess.getRequirementAccess().getGroup_6(), "rule__Requirement__Group_6__0");
					put(grammarAccess.getRequirementAccess().getGroup_7(), "rule__Requirement__Group_7__0");
					put(grammarAccess.getRequirementAccess().getGroup_8(), "rule__Requirement__Group_8__0");
					put(grammarAccess.getRequirementAccess().getGroup_9(), "rule__Requirement__Group_9__0");
					put(grammarAccess.getRequirementAccess().getGroup_10(), "rule__Requirement__Group_10__0");
					put(grammarAccess.getRequirementAccess().getGroup_11(), "rule__Requirement__Group_11__0");
					put(grammarAccess.getRequirementAccess().getGroup_11_3(), "rule__Requirement__Group_11_3__0");
					put(grammarAccess.getRequirementAccess().getGroup_14(), "rule__Requirement__Group_14__0");
					put(grammarAccess.getRequirementAccess().getGroup_14_3(), "rule__Requirement__Group_14_3__0");
					put(grammarAccess.getRequirementAccess().getGroup_15(), "rule__Requirement__Group_15__0");
					put(grammarAccess.getRequirementAccess().getGroup_15_3(), "rule__Requirement__Group_15_3__0");
					put(grammarAccess.getVersionAccess().getGroup(), "rule__Version__Group__0");
					put(grammarAccess.getCommentAccess().getGroup(), "rule__Comment__Group__0");
					put(grammarAccess.getCommentAccess().getGroup_3(), "rule__Comment__Group_3__0");
					put(grammarAccess.getCommentAccess().getGroup_4(), "rule__Comment__Group_4__0");
					put(grammarAccess.getCommentAccess().getGroup_5(), "rule__Comment__Group_5__0");
					put(grammarAccess.getCommentAccess().getGroup_6(), "rule__Comment__Group_6__0");
					put(grammarAccess.getCommentAccess().getGroup_7(), "rule__Comment__Group_7__0");
					put(grammarAccess.getCommentAccess().getGroup_7_3(), "rule__Comment__Group_7_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getModelAccess().getTitleAssignment_3_1(), "rule__Model__TitleAssignment_3_1");
					put(grammarAccess.getModelAccess().getGroupsAssignment_4_2(), "rule__Model__GroupsAssignment_4_2");
					put(grammarAccess.getModelAccess().getGroupsAssignment_4_3_1(), "rule__Model__GroupsAssignment_4_3_1");
					put(grammarAccess.getRequirementGroupAccess().getNameAssignment_2(), "rule__RequirementGroup__NameAssignment_2");
					put(grammarAccess.getRequirementGroupAccess().getDescriptionAssignment_4_1(), "rule__RequirementGroup__DescriptionAssignment_4_1");
					put(grammarAccess.getRequirementGroupAccess().getIdAssignment_5_1(), "rule__RequirementGroup__IdAssignment_5_1");
					put(grammarAccess.getRequirementGroupAccess().getChildrenAssignment_6_2(), "rule__RequirementGroup__ChildrenAssignment_6_2");
					put(grammarAccess.getRequirementGroupAccess().getChildrenAssignment_6_3_1(), "rule__RequirementGroup__ChildrenAssignment_6_3_1");
					put(grammarAccess.getRequirementGroupAccess().getRequirementsAssignment_7_2(), "rule__RequirementGroup__RequirementsAssignment_7_2");
					put(grammarAccess.getRequirementGroupAccess().getRequirementsAssignment_7_3_1(), "rule__RequirementGroup__RequirementsAssignment_7_3_1");
					put(grammarAccess.getRequirementAccess().getTitleAssignment_2_1(), "rule__Requirement__TitleAssignment_2_1");
					put(grammarAccess.getRequirementAccess().getDescriptionAssignment_3_1(), "rule__Requirement__DescriptionAssignment_3_1");
					put(grammarAccess.getRequirementAccess().getTypeAssignment_4_1(), "rule__Requirement__TypeAssignment_4_1");
					put(grammarAccess.getRequirementAccess().getPriorityAssignment_5_1(), "rule__Requirement__PriorityAssignment_5_1");
					put(grammarAccess.getRequirementAccess().getAuthorAssignment_6_1(), "rule__Requirement__AuthorAssignment_6_1");
					put(grammarAccess.getRequirementAccess().getCreatedAssignment_7_1(), "rule__Requirement__CreatedAssignment_7_1");
					put(grammarAccess.getRequirementAccess().getIdAssignment_8_1(), "rule__Requirement__IdAssignment_8_1");
					put(grammarAccess.getRequirementAccess().getStateAssignment_9_1(), "rule__Requirement__StateAssignment_9_1");
					put(grammarAccess.getRequirementAccess().getResolutionAssignment_10_1(), "rule__Requirement__ResolutionAssignment_10_1");
					put(grammarAccess.getRequirementAccess().getDependenciesAssignment_11_2(), "rule__Requirement__DependenciesAssignment_11_2");
					put(grammarAccess.getRequirementAccess().getDependenciesAssignment_11_3_1(), "rule__Requirement__DependenciesAssignment_11_3_1");
					put(grammarAccess.getRequirementAccess().getVersionAssignment_13(), "rule__Requirement__VersionAssignment_13");
					put(grammarAccess.getRequirementAccess().getChildrenAssignment_14_2(), "rule__Requirement__ChildrenAssignment_14_2");
					put(grammarAccess.getRequirementAccess().getChildrenAssignment_14_3_1(), "rule__Requirement__ChildrenAssignment_14_3_1");
					put(grammarAccess.getRequirementAccess().getCommentsAssignment_15_2(), "rule__Requirement__CommentsAssignment_15_2");
					put(grammarAccess.getRequirementAccess().getCommentsAssignment_15_3_1(), "rule__Requirement__CommentsAssignment_15_3_1");
					put(grammarAccess.getVersionAccess().getMajorAssignment_3(), "rule__Version__MajorAssignment_3");
					put(grammarAccess.getVersionAccess().getMinorAssignment_5(), "rule__Version__MinorAssignment_5");
					put(grammarAccess.getVersionAccess().getServiceAssignment_7(), "rule__Version__ServiceAssignment_7");
					put(grammarAccess.getCommentAccess().getSubjectAssignment_3_1(), "rule__Comment__SubjectAssignment_3_1");
					put(grammarAccess.getCommentAccess().getBodyAssignment_4_1(), "rule__Comment__BodyAssignment_4_1");
					put(grammarAccess.getCommentAccess().getAuthorAssignment_5_1(), "rule__Comment__AuthorAssignment_5_1");
					put(grammarAccess.getCommentAccess().getCreatedAssignment_6_1(), "rule__Comment__CreatedAssignment_6_1");
					put(grammarAccess.getCommentAccess().getChildrenAssignment_7_2(), "rule__Comment__ChildrenAssignment_7_2");
					put(grammarAccess.getCommentAccess().getChildrenAssignment_7_3_1(), "rule__Comment__ChildrenAssignment_7_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RequirementsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RequirementsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
