/*
 * generated by Xtext 2.19.0
 */
package requirements.dsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import requirements.dsl.RDSLRuntimeModule
import requirements.dsl.RDSLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RDSLIdeSetup extends RDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RDSLRuntimeModule, new RDSLIdeModule))
	}
	
}
