/*
 * generated by Xtext 2.12.0
 */
package pt.isep.edom.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRequirementsDslScopeProvider extends DelegatingScopeProvider {
}
