/**
 * generated by Xtext 2.19.0
 */
package requirements.dsl.ui.contentassist;

import requirements.dsl.ui.contentassist.AbstractRDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RDSLProposalProvider extends AbstractRDSLProposalProvider {
}
